### ISSUE TITLE
Do you plan to replace your other package with this one?

### ISSUE THREAD

**Issue by rap2hpoutre** [Maatwebsite/Laravel-Excel-Light#1]
In other words: should I start a new project with this one or the other? Will you implement all the functionality (😍) from the other one?

**Comment by patrickbrouwers** [comment]
hey @rap2hpoutre, thanks for your interest. We will probably release a version 3.0 of Laravel-Excel which will support a way to switch between PHPExcel and Spout as drivers.
I wouldn't currently use this package as it's nowhere around stable (and no testcoverage). It's more of an experimental thing currently. This package will probably also disappear and be merged in Laravel-Excel in the future.

**Comment by rap2hpoutre** [comment]
ok thank you!
