### ISSUE TITLE
how to install it on laravel 5 ?

### ISSUE THREAD

**Issue by messi89** [Maatwebsite/Laravel-Excel-Light#2]
how to install this package ? will you release a version with phpexcel/spout ?

**Comment by vlaats** [comment]
Install through repository:
Add this to your composer.json file:

"repositories": [
        {
            "type": "git",
            "url": "https://github.com/Maatwebsite/Laravel-Excel-Light.git"
        }
    ]

Add require:
"maatwebsite/laravel-excel-light": "dev-master"

To use in Controller add using:
use Maatwebsite\ExcelLight\Excel;

**Comment by patrickbrouwers** [comment]
`composer require maatwebsite/laravel-excel-light`
