### ISSUE TITLE
is it possible to use fromModel

### ISSUE THREAD

**Issue by nasirkhan** [Maatwebsite/Laravel-Excel-Light#7]
I was planning to export an excel from the model in via `fromModel` method. In Laravel-Excel package i use this it would be great if i can get the same here. 
thanks

**Comment by patrickbrouwers** [comment]
We are not planning on further developing this package, it was just an experiment. I wouldn't advise using this package in production, is nowhere near stable and ready.

**Comment by nasirkhan** [comment]
thanks for your advice and replying instantly. 

Actually i am facing some issue with exporting a large excel. I read in some posts that the spout performs better for large excels. Do you have any suggestions on exporting around 20K rows using PHPExcel?

**Comment by patrickbrouwers** [comment]
For no? Just use Spout directly :) For later: Laravel-Excel 3.0 wil have a Spout-option built-in.
