### ISSUE TITLE
Could not find package

### ISSUE THREAD

**Issue by damku999** [Maatwebsite/Laravel-Excel-Light#8]
c:\inetpub\wwwroot\odata>composer require maatwebsite/laravel-excel-light

  [InvalidArgumentException]
  Could not find package maatwebsite/laravel-excel-light at any version for your minimum-stability (stable). Check the package spelling or your minimum-stabi
  lity

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--
ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<
packages>]...
(url)

**Comment by jochemfuchs** [comment]
Please note the following from the readme:

```
No plans for further development and/or support. This is just an experiment to imporve the Laravel-Excel library.
```

There is no stable release, nor are we planning to create one at this point. 

That's why your requirement ( minimum-stability (stable).  ) causes you not to be able to install the package.

**Comment by oranges13** [comment]
Since no one deemed it necessary to explain how to get around this, you can install the plugin by adding `dev-master` to the end of your composer directive.

`composer require maatwebsite/laravel-excel-light:dev-master`

**Comment by patrickbrouwers** [comment]
I think @jochemfuchs was pretty clear. You shouldn't get around this. This package is not supported and will not be supported in the future. Use https://github.com/Maatwebsite/Laravel-Excel instead
